In [3]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
def carregaCSV(fileName):
    dir = 'D:\TCC\csv\\'

    fullPath = dir+fileName

    df = pd.read_csv(fullPath, encoding="Latin 1", sep= ";", decimal='.')                  

    return df

In [70]:
dfAno = carregaCSV('total_ano.csv')

In [71]:
dfAno.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899454 entries, 0 to 899453
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   sexo            899454 non-null  int64
 1   idade           899454 non-null  int64
 2   ocupacao        899454 non-null  int64
 3   grau_instrucao  899454 non-null  int64
 4   trimestre       899454 non-null  int64
dtypes: int64(5)
memory usage: 34.3 MB


In [6]:
print(Y)

[1 2 2 ... 1 1 1]


In [11]:
X = dfAno[['idade', 'sexo','grau_instrucao']].values
Y = dfAno['ocupacao'].values

In [12]:
print(X)

[[45  2  4]
 [26  1  4]
 [18  1  3]
 ...
 [36  2  7]
 [41  2  5]
 [53  1  2]]


In [13]:
dfx = pd.DataFrame(X)

In [14]:
dfx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899454 entries, 0 to 899453
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       899454 non-null  int64
 1   1       899454 non-null  int64
 2   2       899454 non-null  int64
dtypes: int64(3)
memory usage: 20.6 MB


In [15]:
dfx.head()

0  1  2
0  45  2  4
1  26  1  4
2  18  1  3
3  22  2  4
4  50  1  7

In [16]:
dfx.nunique()

0    87
1     2
2     7
dtype: int64

In [18]:
dfx.isnull().sum()

0    0
1    0
2    0
dtype: int64

In [19]:
dfx.describe()

0              1              2
count  899454.000000  899454.000000  899454.000000
mean       39.786675       1.432515       4.370221
std        13.811192       0.495425       1.847672
min        14.000000       1.000000       1.000000
25%        28.000000       1.000000       2.000000
50%        39.000000       1.000000       5.000000
75%        50.000000       2.000000       5.000000
max       102.000000       2.000000       7.000000

In [21]:
from sklearn import preprocessing

In [22]:
std = preprocessing.StandardScaler()
std.fit(X)
Xstd = std.transform(X)

In [32]:
print(pd.DataFrame(Xstd, columns=dfx.columns))

               0         1         2
0       0.377471  1.145452 -0.200372
1      -0.998225 -0.873018 -0.200372
2      -1.577466 -0.873018 -0.741594
3      -1.287846  1.145452 -0.200372
4       0.739497 -0.873018  1.423294
...          ...       ...       ...
899449  1.753168  1.145452  1.423294
899450  0.522281 -0.873018  1.423294
899451 -0.274175  1.145452  1.423294
899452  0.087851  1.145452  0.340850
899453  0.956712 -0.873018 -1.282816

[899454 rows x 3 columns]


In [23]:
print('Média 1: {:.2f}'.format(X.mean()), '\nDesvio 1:{:.2f}'.format(X.std()))
print('Média 2: {:.2f}'.format(Xstd.mean()), '\nDesvio 2:{:.2f}'.format(Xstd.std()))

Média 1: 15.20 
Desvio 1:19.20
Média 2: -0.00 
Desvio 2:1.00


In [24]:
minmax = preprocessing.MinMaxScaler()
minmax.fit(X)
X_minmax = minmax.transform(X)


In [25]:
print(pd.DataFrame(X_minmax, columns=dfx.columns))

               0    1         2
0       0.352273  1.0  0.500000
1       0.136364  0.0  0.500000
2       0.045455  0.0  0.333333
3       0.090909  1.0  0.500000
4       0.409091  0.0  1.000000
...          ...  ...       ...
899449  0.568182  1.0  1.000000
899450  0.375000  0.0  1.000000
899451  0.250000  1.0  1.000000
899452  0.306818  1.0  0.666667
899453  0.443182  0.0  0.166667

[899454 rows x 3 columns]


In [27]:
print('Média 1: {:.2f}'.format(X.mean()), '\nDesvio 1:{:.2f}'.format(X.std()))
print('Média 2: {:.2f}'.format(X_minmax.mean()), '\nDesvio 2:{:.2f}'.format(X_minmax.std()))

Média 1: 15.20 
Desvio 1:19.20
Média 2: 0.43 
Desvio 2:0.37


In [29]:
robust_scaler =  preprocessing.RobustScaler()
robust_scaler.fit(X)
X_robust = robust_scaler.transform(X)

In [30]:
print(pd.DataFrame(X_robust, columns=dfx.columns))

               0    1         2
0       0.272727  1.0 -0.333333
1      -0.590909  0.0 -0.333333
2      -0.954545  0.0 -0.666667
3      -0.772727  1.0 -0.333333
4       0.500000  0.0  0.666667
...          ...  ...       ...
899449  1.136364  1.0  0.666667
899450  0.363636  0.0  0.666667
899451 -0.136364  1.0  0.666667
899452  0.090909  1.0  0.000000
899453  0.636364  0.0 -1.000000

[899454 rows x 3 columns]


In [31]:
print('Média 1: {:.2f}'.format(X.mean()), '\nDesvio 1:{:.2f}'.format(X.std()))
print('Média 2: {:.2f}'.format(X_robust.mean()), '\nDesvio 2:{:.2f}'.format(X_robust.std()))

Média 1: 15.20 
Desvio 1:19.20
Média 2: 0.09 
Desvio 2:0.64


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_trainset, X_testset, Ytrainset, Y_testset = train_test_split(Xstd,Y,test_size=0.3,random_state=3)

In [13]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "loss": ["hinge","log","squared_hinge", "modified_huber", "perceptron"]
    ,"alpha": [0.0001,0.001,0.01, 0.1]
    ,"penalty": ["l2","l1","elasticnet","none"]
}

clf = SGDClassifier(max_iter=50)
grid = GridSearchCV(clf, param_grid=params, cv=10)

In [14]:
grid.fit(X_trainset, Ytrainset)

GridSearchCV(cv=10, estimator=SGDClassifier(max_iter=50),
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1],
                         'loss': ['hinge', 'log', 'squared_hinge',
                                  'modified_huber', 'perceptron'],
                         'penalty': ['l2', 'l1', 'elasticnet', 'none']})

In [17]:
print(grid.best_params_)

{'alpha': 0.0001, 'loss': 'hinge', 'penalty': 'l2'}


In [15]:
grid_predictions = grid.predict(X_testset)

In [16]:
from sklearn.metrics import accuracy_score
print('Acurácia: {:.2f}'.format(accuracy_score(Y_testset, grid_predictions)))

Acurácia: 0.91


In [17]:
clf = SGDClassifier(loss='hinge', penalty='l2',alpha=0.0001, max_iter=50)
clf.fit(X_trainset, Ytrainset)

SGDClassifier(max_iter=50)

In [18]:
Y_Pred = clf.predict(X_testset)
print('Acurácia: {:.2f}'.format(accuracy_score(Y_testset, Y_Pred)))

Acurácia: 0.91


In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
cm = confusion_matrix(Y_testset, Y_Pred)

In [21]:
print(cm)

[[246380      0]
 [ 23457      0]]


In [22]:
from sklearn.metrics import accuracy_score, classification_report

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

treeClf = DecisionTreeClassifier(random_state=0)
treeClf = treeClf.fit(X_trainset,Ytrainset)

print('Acurácia:', treeClf.score(X_trainset,Ytrainset))
tree_predict = treeClf.predict(X_testset)
print('Acurácia de previsão:', accuracy_score(Y_testset,tree_predict))
print(classification_report(Y_testset, tree_predict))

Acurácia: 0.9130042549677025
Acurácia de previsão: 0.9130475064576021
              precision    recall  f1-score   support

           1       0.91      1.00      0.95    246380
           2       0.20      0.00      0.00     23457

    accuracy                           0.91    269837
   macro avg       0.56      0.50      0.48    269837
weighted avg       0.85      0.91      0.87    269837



In [33]:
# Sample
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier

In [28]:
print(dfx)

         0  1  2
0       45  2  4
1       26  1  4
2       18  1  3
3       22  2  4
4       50  1  7
...     .. .. ..
899449  64  2  7
899450  47  1  7
899451  36  2  7
899452  41  2  5
899453  53  1  2

[899454 rows x 3 columns]


In [79]:
# Separando as features e o target
Xups = dfx
Yups = dfAno['ocupacao']

# Concatenando X e y para facilitar a reamostragem
df_combined = pd.concat([Xups, Yups], axis=1)

# Separando as classes majoritária e minoritária
df_majority = df_combined[df_combined['ocupacao'] == 1]  
df_minority = df_combined[df_combined['ocupacao'] == 2]

# Sobreamostrando a classe minoritária
df_minority_upsampled = resample(df_minority,
                                 replace=True,     # Permite amostragem com reposição
                                 n_samples=len(df_majority),  # Para igualar o número de exemplos da classe majoritária
                                 random_state=42)  # Para reprodutibilidade

# Combinando a classe majoritária com a nova classe minoritária sobreamostrada
df_upsampled = pd.concat([df_majority, df_minority_upsampled])


# Separando novamente em X e y
X_upsampled = df_upsampled.drop('ocupacao', axis=1)
y_upsampled = df_upsampled['ocupacao']

# Dividindo o dataset em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X_upsampled, y_upsampled, random_state=42)


In [81]:
df_upsampled.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1642436 entries, 0 to 31473
Data columns (total 4 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   0         1642436 non-null  int64
 1   1         1642436 non-null  int64
 2   2         1642436 non-null  int64
 3   ocupacao  1642436 non-null  int64
dtypes: int64(4)
memory usage: 62.7 MB


In [80]:
# Treinando o modelo
clf = RandomForestClassifier(random_state=0)
clf.fit(X_train, y_train)
print('Acurácia:', clf.score(X_train,y_train))
# Fazendo previsões
y_pred = clf.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6513138614432059
Acurácia de previsão: 0.6499199968826791
              precision    recall  f1-score   support

           1       0.64      0.69      0.66    204876
           2       0.66      0.61      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [82]:
clf = SGDClassifier(max_iter=1000)
clf.fit(X_train, y_train)
print('Acurácia:', clf.score(X_train,y_train))
# Fazendo previsões
y_pred = clf.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6350696972870379
Acurácia de previsão: 0.6347522825851357
              precision    recall  f1-score   support

           1       0.66      0.55      0.60    204876
           2       0.62      0.71      0.66    205733

    accuracy                           0.63    410609
   macro avg       0.64      0.63      0.63    410609
weighted avg       0.64      0.63      0.63    410609



In [ ]:
# Verificando hiperparametros

In [61]:
params = {
    "loss": ["hinge","log","squared_hinge", "modified_huber", "perceptron"]
    ,"alpha": [0.0001,0.001,0.01, 0.1]
    ,"penalty": ["l2","l1","elasticnet","none"]
}

clf = SGDClassifier(max_iter=1000)
grid = GridSearchCV(clf, param_grid=params, cv= 3, scoring="accuracy", n_jobs = -1)
#GridSearchCV(clf, param_grid=params, cv=3)

In [62]:
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SGDClassifier(), n_jobs=-1,
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1],
                         'loss': ['hinge', 'log', 'squared_hinge',
                                  'modified_huber', 'perceptron'],
                         'penalty': ['l2', 'l1', 'elasticnet', 'none']},
             scoring='accuracy')

In [63]:
print(grid.best_params_)

{'alpha': 0.0001, 'loss': 'hinge', 'penalty': 'l1'}


In [64]:
clf = SGDClassifier(loss='hinge', penalty='l1',alpha=0.0001, max_iter=1000)
clf.fit(X_train, y_train)

SGDClassifier(penalty='l1')

In [65]:
print('Acurácia:', clf.score(X_train,y_train))
# Fazendo previsões
y_pred = clf.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6403829433840953
Acurácia de previsão: 0.6398715079309026
              precision    recall  f1-score   support

           1       0.61      0.76      0.68    204876
           2       0.68      0.52      0.59    205733

    accuracy                           0.64    410609
   macro avg       0.65      0.64      0.64    410609
weighted avg       0.65      0.64      0.63    410609



In [66]:
# DecisionTree

dtc = DecisionTreeClassifier()
dtc = dtc.fit(X_train, y_train)

print('Acurácia:', dtc.score(X_train,y_train))
dtc_pred = dtc.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,dtc_pred))
print(classification_report(y_test, dtc_pred))

Acurácia: 0.6513154850478192
Acurácia de previsão: 0.649932173917279
              precision    recall  f1-score   support

           1       0.64      0.68      0.66    204876
           2       0.66      0.62      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [83]:
params = {
    "criterion": ["gini","entropy"]
    ,"max_depth":[None,2,3,5,7,10]
    ,"min_samples_leaf":[1,3,5,7,10]
}

grid = GridSearchCV(dtc, param_grid=params, cv=3, scoring="accuracy")

In [84]:
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2, 3, 5, 7, 10],
                         'min_samples_leaf': [1, 3, 5, 7, 10]},
             scoring='accuracy')

In [85]:
print(grid.best_params_)

{'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1}


In [86]:
dtc = DecisionTreeClassifier(criterion= 'gini', max_depth= None, min_samples_leaf= 1)
dtc = dtc.fit(X_train, y_train)

print('Acurácia:', dtc.score(X_train,y_train))
dtc_pred = dtc.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,dtc_pred))
print(classification_report(y_test, dtc_pred))

Acurácia: 0.6513154850478192
Acurácia de previsão: 0.649932173917279
              precision    recall  f1-score   support

           1       0.64      0.68      0.66    204876
           2       0.66      0.62      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [94]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'min_samples_split': list(range(2, 20))
    ,'min_samples_leaf': list(range(1, 20))
    ,"max_depth":[None,2,3,5,7,10]
    ,"criterion": ["gini","entropy"]
}

random_search = RandomizedSearchCV(dtc, param_distributions=param_dist, scoring="accuracy",
                                   n_iter=1000, cv=3, random_state=42)
random_search.fit(X_train, y_train)


RandomizedSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_iter=1000,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [None, 2, 3, 5, 7, 10],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19],
                                        'min_samples_split': [2, 3, 4, 5, 6, 7,
                                                              8, 9, 10, 11, 12,
                                                              13, 14, 15, 16,
                                                              17, 18, 19]},
                   random_state=42, scoring='accuracy')

In [95]:
print(random_search.best_params_)

{'min_samples_split': 3, 'min_samples_leaf': 1, 'max_depth': None, 'criterion': 'entropy'}


In [112]:
dtc = DecisionTreeClassifier(criterion= 'entropy', max_depth= None, min_samples_leaf= 1, min_samples_split=3
                             
                            )
dtc = dtc.fit(X_train, y_train)

print('Acurácia:', dtc.score(X_train,y_train))
dtc_pred = dtc.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,dtc_pred))
print(classification_report(y_test, dtc_pred))

Acurácia: 0.6513154850478192
Acurácia de previsão: 0.649932173917279
              precision    recall  f1-score   support

           1       0.64      0.68      0.66    204876
           2       0.66      0.62      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [113]:
# RandomForestClassifier
rfclf = RandomForestClassifier()
rfclf.fit(X_train, y_train)

RandomForestClassifier()

In [114]:
print('Acurácia:', rfclf.score(X_train,y_train))
# Fazendo previsões
y_pred = rfclf.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.651308990629366
Acurácia de previsão: 0.6499346093241989
              precision    recall  f1-score   support

           1       0.64      0.69      0.66    204876
           2       0.66      0.61      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [121]:
#Hiperparametros
param_dist = {
    "n_estimators": list(range(10,100,10))
    ,"max_depth": list(range(0,11))
    #,"max_features":[1,2,3]
    ,"min_samples_split": list(range(2, 11))
    ,"criterion": ["gini","entropy"]
}

In [122]:
rf_random_search = RandomizedSearchCV(rfclf, param_distributions=param_dist, scoring="accuracy",
                                   n_iter=50, cv=3, random_state=42)

In [123]:
rf_random_search.fit(X_train, y_train)

D:\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
12 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "D:\anaconda3\lib\site-packages\joblib\parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "D:\anaconda3\lib\site-packages\joblib\parallel.py", line 1847, in _get_se

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=50,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [0, 1, 2, 3, 4, 5, 6, 7, 8,
                                                      9, 10],
                                        'min_samples_split': [2, 3, 4, 5, 6, 7,
                                                              8, 9, 10],
                                        'n_estimators': [10, 20, 30, 40, 50, 60,
                                                         70, 80, 90]},
                   random_state=42, scoring='accuracy')

In [124]:
print(rf_random_search.best_params_)

{'n_estimators': 60, 'min_samples_split': 3, 'max_depth': 10, 'criterion': 'gini'}


In [125]:
rfclf = RandomForestClassifier(n_estimators=60,min_samples_split=3,max_depth=10,criterion='gini')
rfclf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_split=3, n_estimators=60)

In [126]:
print('Acurácia:', rfclf.score(X_train,y_train))
# Fazendo previsões
y_pred = rfclf.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6510467784843164
Acurácia de previsão: 0.6498298868266404
              precision    recall  f1-score   support

           1       0.64      0.69      0.66    204876
           2       0.66      0.61      0.64    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [127]:
from sklearn.ensemble import  GradientBoostingClassifier

# Gradient Boosting
gbm = GradientBoostingClassifier(random_state=42)
gbm.fit(X_train, y_train)
y_pred_gbm = gbm.predict(X_test)

print("\nGradient Boosting Metrics:")
print(classification_report(y_test, y_pred_gbm, target_names=['Ocupado', 'Desocupado']))


Gradient Boosting Metrics:
              precision    recall  f1-score   support

     Ocupado       0.64      0.69      0.66    204876
  Desocupado       0.66      0.61      0.63    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [128]:
print('Acurácia:', gbm.score(X_train,y_train))
# Fazendo previsões
y_pred = gbm.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6496301834592033
Acurácia de previsão: 0.6492478245727688
              precision    recall  f1-score   support

           1       0.64      0.69      0.66    204876
           2       0.66      0.61      0.63    205733

    accuracy                           0.65    410609
   macro avg       0.65      0.65      0.65    410609
weighted avg       0.65      0.65      0.65    410609



In [84]:
from sklearn.linear_model import LogisticRegression

In [130]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [131]:
print('Acurácia:', lr.score(X_train,y_train))
# Fazendo previsões
y_pred = lr.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6425106772298382
Acurácia de previsão: 0.641527584636479
              precision    recall  f1-score   support

           1       0.64      0.63      0.64    204876
           2       0.64      0.66      0.65    205733

    accuracy                           0.64    410609
   macro avg       0.64      0.64      0.64    410609
weighted avg       0.64      0.64      0.64    410609



In [86]:
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
grid_search = GridSearchCV(estimator=lr, param_grid=grid, n_jobs=-1, cv=10, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X_train, y_train)
print(grid_result.best_params_)

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}


In [88]:
lr = LogisticRegression(C=0.01, penalty='l2', solver='liblinear')
lr.fit(X_train, y_train)
print('Acurácia:', lr.score(X_train,y_train))
# Fazendo previsões
y_pred = lr.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,y_pred))
# Avaliando o modelo
print(classification_report(y_test, y_pred))

Acurácia: 0.6425139244390649
Acurácia de previsão: 0.641525149229559
              precision    recall  f1-score   support

           1       0.64      0.63      0.64    204876
           2       0.64      0.66      0.65    205733

    accuracy                           0.64    410609
   macro avg       0.64      0.64      0.64    410609
weighted avg       0.64      0.64      0.64    410609



In [90]:
from sklearn.naive_bayes import GaussianNB

In [133]:
gncl = GaussianNB()
gncl.fit(X_train, y_train)

GaussianNB()

In [134]:
print('Acurácia:', gncl.score(X_train,y_train))
nb_predict = gncl.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,nb_predict))
print(classification_report(y_test, nb_predict))

Acurácia: 0.6380546943686086
Acurácia de previsão: 0.637465325893977
              precision    recall  f1-score   support

           1       0.65      0.59      0.62    204876
           2       0.63      0.68      0.65    205733

    accuracy                           0.64    410609
   macro avg       0.64      0.64      0.64    410609
weighted avg       0.64      0.64      0.64    410609



In [92]:
params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
gs_NB = GridSearchCV(estimator=gncl, 
                 param_grid=params_NB, 
                 cv=10,   # use any cross validation technique 
                 verbose=0, 
                 scoring='accuracy') 
gs_NB.fit(X_train, y_train)

gs_NB.best_params_

{'var_smoothing': 0.0001873817422860383}

In [94]:
from sklearn.neighbors import KNeighborsClassifier

In [93]:
gncl = GaussianNB(var_smoothing=0.0001873817422860383)
gncl.fit(X_train, y_train)
print('Acurácia:', gncl.score(X_train,y_train))
nb_predict = gncl.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,nb_predict))
print(classification_report(y_test, nb_predict))

Acurácia: 0.6387674567938517
Acurácia de previsão: 0.6380400819270888
              precision    recall  f1-score   support

           1       0.65      0.60      0.62    204876
           2       0.63      0.68      0.65    205733

    accuracy                           0.64    410609
   macro avg       0.64      0.64      0.64    410609
weighted avg       0.64      0.64      0.64    410609



In [136]:
# KNN
kncl = KNeighborsClassifier()
kncl.fit(X_train, y_train)

KNeighborsClassifier()

In [137]:
print('Acurácia:', kncl.score(X_train,y_train))
knn_predict = kncl.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,knn_predict))
print(classification_report(y_test, knn_predict))

D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Acurácia: 0.5926660156012167


D:\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Acurácia de previsão: 0.5915652116733925
              precision    recall  f1-score   support

           1       0.59      0.60      0.59    204876
           2       0.59      0.58      0.59    205733

    accuracy                           0.59    410609
   macro avg       0.59      0.59      0.59    410609
weighted avg       0.59      0.59      0.59    410609



In [96]:
grid_params = { 'n_neighbors' : [5,7,9,11,13,15],
               'weights' : ['uniform','distance'],
               'metric' : ['minkowski','euclidean','manhattan']}

gs = GridSearchCV(kncl, grid_params, verbose = 1, cv=3, n_jobs = -1)
g_res = gs.fit(X_train, y_train)
g_res.best_params_

Fitting 3 folds for each of 36 candidates, totalling 108 fits


{'metric': 'minkowski', 'n_neighbors': 15, 'weights': 'distance'}

In [97]:
# KNN
kncl = KNeighborsClassifier(metric= 'minkowski',n_neighbors= 15, weights='distance')
kncl.fit(X_train, y_train)
print('Acurácia:', kncl.score(X_train,y_train))
knn_predict = kncl.predict(X_test)
print('Acurácia de previsão:', accuracy_score(y_test,knn_predict))
print(classification_report(y_test, knn_predict))

Acurácia: 0.6310066267422292
Acurácia de previsão: 0.630047076415763
              precision    recall  f1-score   support

           1       0.62      0.68      0.65    204876
           2       0.64      0.58      0.61    205733

    accuracy                           0.63    410609
   macro avg       0.63      0.63      0.63    410609
weighted avg       0.63      0.63      0.63    410609

